const data = {
  products:[
    {
      _id: '1',
      name: 'PUMA SEY56',
      category: 'Schuhe',
      image: '/images/p1.jpg',
      price: '90,00',
      rating:4.5,
      numReviews:10,
      description: 'hochwertiges Produkt',
    },
    {
      _id: '2',
      name: 'Converse 65ZU',
      category: 'Schuhe',
      image: '/images/p2.jpg',
      price: '80,00',
      rating:4.8,
      numReviews:20,
      description: 'hochwertiges Produkt',
    },
    {
      _id: '3',
      name: 'New Balance 997H',
      category: 'Schuhe',
      image: '/images/p3.jpg',
      price: '110,00',
      rating:4.1,
      numReviews:12,
      description: 'hochwertiges Produkt',
    },
    {
      _id: '4',
      name: 'Adidas',
      category: 'Schuhe',
      image: '/images/p4.jpg',
      price: '130,00',
      rating:4.8,
      numReviews:21,
      description: 'hochwertiges Produkt',
    },
    {
      _id: '5',
      name: 'PUMA 720T',
      category: 'Schuhe',
      image: '/images/p5.jpg',
      price: '190,00',
      rating:5,
      numReviews:8,
      description: 'hochwertiges Produkt',
    },
    {
      _id: '6',
      name: 'FILA Damen',
      category: 'Schuhe',
      image: '/images/p6.jpg',
      price: '65,00',
      rating:4.1,
      numReviews:54,
      description: 'hochwertiges Produkt',
    },
  ]
}

export default data;